### ISSUE TITLE
Use dynamic queries in @ExpectedDatabase

### ISSUE THREAD

**Issue by jonsimon** [springtestdbunit/spring-test-dbunit#101]
I would love to use a dynamic query for the query property in @ExpectedDatabase.  For example, a query with parameters that gets filled in before afterTestMethod is called.

It is my impression that the query has to be fully defined when using @ExpectedDatabase annotation.

Is there a way to do that now?  If not, would like to recommend this as an enhancement.

**Comment by philwebb** [comment]
There's not currently any way to do this. If you've got any ideas on how to implement this I'd be happy to look at a pull-request. Unfortunately, I have so little time at the moment that I won't be able to implement this myself.
