### ISSUE TITLE
NoClassDefFoundError: ITableMetaData

### ISSUE THREAD

**Issue by raderio** [springtestdbunit/spring-test-dbunit#130]
> java.lang.NoClassDefFoundError: org/dbunit/dataset/ITableMetaData
> 	at com.github.springtestdbunit.assertion.DatabaseAssertionMode.<clinit>(DatabaseAssertionMode.java:46)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.lang.Class.getEnumConstantsShared(Class.java:3320)
> 	at java.lang.Class.enumConstantDirectory(Class.java:3341)
> 	at java.lang.Enum.valueOf(Enum.java:232)
> 	at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:483)
> 	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:347)
> 	at java.lang.reflect.Method.getDefaultValue(Method.java:606)
> 	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
> 	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
> 	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
> 	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
> 	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
> 	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
> 	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:597)
> 	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:588)
> 	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:630)
> 	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:207)
> 	at org.junit.runners.model.FrameworkMethod.getAnnotations(FrameworkMethod.java:187)
> 	at org.junit.runners.model.TestClass.addToAnnotationLists(TestClass.java:84)
> 	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:66)
> 	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
> 	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
> 	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
> 	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<init>(SpringJUnit4ClassRunner.java:138)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
> 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
> 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
> 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
> 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
> 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
> 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
> 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
> 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
> 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: org.dbunit.dataset.ITableMetaData
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 65 more

**Comment by djselzlein** [comment]
What about this exception? Could you provide more info?

**Comment by raderio** [comment]
build.gradle

```
compile group: "mysql", name: "mysql-connector-java", version: "5.1.40"
testCompile group: "com.github.springtestdbunit", name: "spring-test-dbunit", version: "1.3.0"
```

Why I get this exception? I should include more dependencies?

**Comment by raderio** [comment]
So, based on https://sourceforge.net/p/unitils/discussion/570578/thread/53ec2b68/
I should add dependency to "org.dbunit/dbunit". Can you please add this to documentation?
Thanks.
