### ISSUE TITLE
Problems with MicrosoftSqlDatabaseOperationLookup

### ISSUE THREAD

**Issue by dayanfcosta** [springtestdbunit/spring-test-dbunit#141]
When I set MicrosoftSqlDatabaseOperationLookup on my @DbUnitConfiguration the transaction doesn't do the rollback, keeping trash on my database. What can be happening?

**Comment by nach-o-man** [comment]
@dayancosta you should wait for DBUnit version 2.5.4. [Related topic](https://sourceforge.net/p/dbunit/bugs/309/)
