### ISSUE TITLE
Exporting data into XML file

### ISSUE THREAD

**Issue by SunithaR** [springtestdbunit/spring-test-dbunit#37]
Is there an annotation that can be used to export data in a particular database table into an XML file?

This would be useful, when I need to backup data, put in test data and when done with my tests put back the backed up data.

**Comment by lllkc** [comment]
What if I have two databases to be rollbacked?

**Comment by FingolfinTEK** [comment]
You should then be using either a JTA transaction manager or if XA is for some reason too heavyweight for you, Spring's own ChainedTransactionManager.

**Comment by lllkc** [comment]
Good idea! Thanks for pointing it out.
