### ISSUE TITLE
Multiple datasource support

### ISSUE THREAD

**Issue by nyilmaz** [springtestdbunit/spring-test-dbunit#42]
I'm curious, whether you may implement multiple datasource support. I have forked your project and tried to give that support which we can provide datasource files (xmls) to different datasources. Although some tests related to @Transactional are failing right now, maybe you want to check out mine. The usage is simply;

```
@DbUnitConfiguration(connections="conn1,conn2")
@DatabaseSetup(connections = {@DatabaseConnectionSetup(connection="conn1", value="xxx.xml")})
```

**Comment by haocao** [comment]
Thanks for your fix, but could you put it into maven http://www.mvnrepository.com/, thanks.

**Comment by philwebb** [comment]
http://repo1.maven.org/maven2/com/github/springtestdbunit/spring-test-dbunit/1.2.1/

**Comment by nyilmaz** [comment]
Thanks for your effort :)

**Comment by haocao** [comment]
It worked, thanks for your helps.
