### ISSUE TITLE
Provide a way to replace tokens in the data set with values generated in test runtime.

### ISSUE THREAD

**Issue by acisser** [springtestdbunit/spring-test-dbunit#60]
Look at the most voted answer for the following post

http://stackoverflow.com/questions/2856840/date-relative-to-current-in-the-dbunit-dataset

I'm imaging something like this:

```java
@Before
public void onSetup(@DatabaseSetupRelatedAnnotation ReplacementDataSet replacementDataSet){}
```

```java
@Test
@DatabaseSetup("initDataset.xml")
@ExpectedDatabase("expectedDataset.xml")
public void testXX(@ExpectedDatabaseRelatedAnnotation ReplacementDataSet replacementDataSet){}
```

I remember seeing BDD frameworks before like cucumber injecting values in test method arguments.

**Comment by philwebb** [comment]
I've added a DataSetModifier interface which you can use to modify the IDataSet before it's used to verify results. [Here's an example](https://github.com/springtestdbunit/spring-test-dbunit/blob/master/spring-test-dbunit/src/test/java/com/github/springtestdbunit/expected/ExpectedQueryWithModifierOnMethodTest.java)

**Comment by a5rar** [comment]
How would you modify dataset before it is inserted.  using @DatabseSetup?

**Comment by philwebb** [comment]
@a5rar You currently can't. The modifier is only for `@ExpectedDatabase`.
