### ISSUE TITLE
Trouble using DatabaseSetup

### ISSUE THREAD

**Issue by brunifrancesco** [springtestdbunit/spring-test-dbunit#61]
When I use the `@DatabaseSetup` annotation, loading a scenario from XML file, the `CleanInsert` is not performed. 

I use the 1.0.0 version of spring-test-dbunit and 4.1.1.RELEASE of the Spring Framework.

**Comment by philwebb** [comment]
Do you get the same error with 1.2.0.BUILD-SNAPSHOT? Perhaps you can provide a project that reproduces the problem?
