### ISSUE TITLE
Treatment can inquire about the number of files in the @DatabaseSetup annotation

### ISSUE THREAD

**Issue by bluepoet** [springtestdbunit/spring-test-dbunit#62]
Do not be DatabaseOperation.CLEAN_INSERT operations on multiple files in DatabaseSetup annotation ?
I would like to know whether the process in which version i heard it has been patched in version 1.1.1-SNAPSHOT .

https://github.com/springtestdbunit/spring-test-dbunit/pull/56

**Comment by philwebb** [comment]
#56 will be part of the upcoming 1.2.0 release.
