### ISSUE TITLE
Spring container couldn't initialize when @DbUnitConfiguration is in use

### ISSUE THREAD

**Issue by tmhung88** [springtestdbunit/spring-test-dbunit#66]
I tried to use `datasetLoader` of `@DbUnitConfiguration`, and not declare the attribute `databaseConnetion`. Then I received an exception when the Spring container was initializing. I figured out it's caused by an empty string as the default value of `databaseConnection` attribute.

```java
        if (configuration != null) {
            if (logger.isDebugEnabled()) {
                logger.debug("Using @DbUnitConfiguration configuration");
            }
            databaseConnectionBeanNames = configuration.databaseConnection(); // default value is an empty string
            dataSetLoaderClass = configuration.dataSetLoader();
            dataSetLoaderBeanName = configuration.dataSetLoaderBean();
            databaseOperationLookupClass = configuration.databaseOperationLookup();
        }
    
    
        if (ObjectUtils.isEmpty(databaseConnectionBeanNames))  // that snippet couldn't be executed as the array had an empty string
       { 
            databaseConnectionBeanNames = new String[] { getDatabaseConnectionUsingCommonBeanNames(testContext) };
        }
```

**Comment by philwebb** [comment]
Thanks, that should have been fixed already. See c1e4d877ff14cccc027ecd62ee10a952d35721b4 and the 1.2.1 release.

**Comment by tmhung88** [comment]
@philwebb The artifact 1.2.1 had been published into Maven Repository 8 Jan before you committed the fix at 9 Jan. Please re-build and publish the artifact.

http://mvnrepository.com/artifact/com.github.springtestdbunit/spring-test-dbunit/1.2.1

**Comment by philwebb** [comment]
Will have to pick it up in 1.3.0 now.
