### ISSUE TITLE
@ExpectedDatabases can't work when using multiple datasources

### ISSUE THREAD

**Issue by haocao** [springtestdbunit/spring-test-dbunit#68]
I got an issue when using @ExpectedDatabases like this:

```java
@Test
@DatabaseSetup(connection = DataSourceKeys.DATA_SOURCE_1, value = "AfterUpdateDataSource1.xml")
@DatabaseSetup(connection = DataSourceKeys.DATA_SOURCE_2, value = "AfterUpdateDataSource2.xml")
@ExpectedDatabases({
        @ExpectedDatabase(connection = DataSourceKeys.DATA_SOURCE_1, value = "AfterUpdateNotNullDataSource1.xml", assertionMode = DatabaseAssertionMode.NON_STRICT),
        @ExpectedDatabase(connection = DataSourceKeys.DATA_SOURCE_2, value = "AfterUpdateNotNullDataSource2.xml", assertionMode = DatabaseAssertionMode.NON_STRICT)
    })
```

I suppose the `ExpectedDatabases` annotation can be works for two datasources but, only one annotation (DATA_SOURCE_2) can work, could you help take a look at this issue?

**Comment by philwebb** [comment]
I'm not following. Can you provide a sample application?

**Comment by haocao** [comment]
NP, the use case is that I want to using two databases and expect the result from these two databases.
I try to using these two way:
1.
    @Test
    @DatabaseSetup(connection = DataSourceKeys.DATA_SOURCE_1, value = "EmptyDataSource1.xml")
    @DatabaseSetup(connection = DataSourceKeys.DATA_SOURCE_2, value = "EmptyDataSource2.xml")
    @ExpectedDatabase(connection = DataSourceKeys.DATA_SOURCE_1, value = "AfterInsertDataSource1.xml", assertionMode = DatabaseAssertionMode.NON_STRICT)
    @ExpectedDatabase(connection = DataSourceKeys.DATA_SOURCE_2, value = "AfterInsertDataSource2.xml", assertionMode = DatabaseAssertionMode.NON_STRICT)
    public void insert() throws Exception {
        fooRepository.insert(buildDataSourceOneModelOne());
        fooRepository.insert(buildDataSourceOneModelTwo());
        barRepository.insert(buildDataSourceTwoModelOne());
    }

2.
    @Test
    @DatabaseSetup(connection = DataSourceKeys.DATA_SOURCE_1, value = "EmptyDataSource1.xml")
    @DatabaseSetup(connection = DataSourceKeys.DATA_SOURCE_2, value = "EmptyDataSource2.xml")
@ExpectedDatabase{
    @ExpectedDatabase(connection = DataSourceKeys.DATA_SOURCE_1, value = "AfterInsertDataSource1.xml", assertionMode = DatabaseAssertionMode.NON_STRICT),
    @ExpectedDatabase(connection = DataSourceKeys.DATA_SOURCE_2, value = "AfterInsertDataSource2.xml", assertionMode = DatabaseAssertionMode.NON_STRICT)
}
    public void insert() throws Exception {
        fooRepository.insert(buildDataSourceOneModelOne());
        fooRepository.insert(buildDataSourceOneModelTwo());
        barRepository.insert(buildDataSourceTwoModelOne());
    }

AfterInsertDataSource1.xml:
<?xml version='1.0' encoding='UTF-8'?>
<dataset>
    <rdb_foo id="1" name="testInsert" />
</dataset>

AfterInsertDataSource2.xml:
<?xml version='1.0' encoding='UTF-8'?>
<dataset>
    <rdb_bar id="1" name="AAA" type="1"/>
</dataset>

But they can't give the right expect result as AfterInsertDataSource1.xml's excpect data doesn't work.

Could you help to make a demo like above? I think you will get the same result as mine, thanks.

**Comment by philwebb** [comment]
1 and 2 should be equivalent. Can you share a project on github that reproduces the issue, I still don't really understand what's actually failing.

**Comment by haocao** [comment]
I made a code sample like https://github.com/haocao/spring-dbunit-test, please take your time to take a look at it, thanks.

**Comment by philwebb** [comment]
Thanks for the sample. Looks like we have a bug with the way that `@ExpectedDatabase` annotations at the method level are designed to override those at the class level. This doesn't work so well with repeatable annotations.

I think if you add `override=false` to your `@ExpectedDatabase` annotations things should work as expected.

**Comment by haocao** [comment]
Really appreciate for your suggestions, it works right now.

**Comment by martiniD** [comment]
Another occurence is IMHO if the same table needs to be validated against the aggregate of 2 xml files(both files define a dataset for the same table).
For this scenario, "override=false" does not work.

**Comment by PierrickPuimeanChieze** [comment]
I was able to use this feature using the @ExpectedDatabases annotation with Java 7 and BDUnit 1.2.1. Maybe this bug can be closed ?

**Comment by haocao** [comment]
Yes, I will close it.

**Comment by limeng32** [comment]
This issue help me a lot.
