### ISSUE TITLE
Custom DatabaseAssertionMode for trimming spaces

### ISSUE THREAD

**Issue by sandeeprajub4u** [springtestdbunit/spring-test-dbunit#81]
We have mostly char columns in the table. When the dbunit compares the data it compares with padding spaces and we end up writing a expected dataset with spaces. We have exactly same issue as defined below.
http://sourceforge.net/p/dbunit/mailman/dbunit-developer/thread/200806290220.m5T2KAPO021200@49zxpd1.ch3.sourceforge.com/ 

Solution 1) Provide an flag in ExpectedDatabase which trims the data on actual before comparison
Solution 2) Adding new DatabaseAssertionMode custom, which allows us to inject our custom DatabaseAssertion

Can you please let us know if any of the solutions are feasible

**Comment by philwebb** [comment]
I'm not keen on the flag, but a new `DatabaseAssertionMode` doesn't sound too bad. Feel free to submit a pull-request if you have time.
