### ISSUE TITLE
Set default assertion mode at class level

### ISSUE THREAD

**Issue by sgrimm-sg** [springtestdbunit/spring-test-dbunit#84]
Feature request: It'd be handy to be able to put an annotation on a test class that would change the default assertion mode for any `@ExpectedDatabase` annotations on methods. We usually use `NON_STRICT_UNORDERED` mode and it's a little ugly-looking to have to specify that explicitly on every test method.

To be more concrete, I'm asking for something along the lines of,

```java
@DbUnitConfiguration(defaultAssertionMode = DatabaseAssertionMode.NON_STRICT_UNORDERED)
public class MyDbUnitTest {
    @Test
    @ExpectedDatabase("MyDataSet.xml")
    public void testSomeDbStuff() { ... }
}
```

which would be equivalent to what we do today,

```java
public class MyDbUnitTest {
    @Test
    @ExpectedDatabase(value = "MyDataSet.xml", assertionMode = DatabaseAssertionMode.NON_STRICT_UNORDERED)
    public void testSomeDbStuff() { ... }
}
```

**Comment by philwebb** [comment]
It's a nice idea but I can't see an easy way to implement it without breaking back compatibility. If you come up with any ideas feel free to submit a pull-request.
