### ISSUE TITLE
How to use MicrosoftSqlDatabaseOperationLookup

### ISSUE THREAD

**Issue by sandeeprajub4u** [springtestdbunit/spring-test-dbunit#91]
We have identity columns in the table. Can you please give us an example on how to use 
`@DatabaseSetup` with type as `MicrosoftSqlDatabaseOperationLookup`

**Comment by philwebb** [comment]
Use `@DbUnitConfiguration(databaseOperationLookup=MicrosoftSqlDatabaseOperationLookup.class)`
