### ISSUE TITLE
Broken link under FAQ page

### ISSUE THREAD

**Issue by vict0r81** [springtestdbunit/spring-test-dbunit#92]
Hey!
Thanks for your project!
Just found a trivial issue with broken link on FAQ page http://springtestdbunit.github.io/spring-test-dbunit/faq.html

In the section "Is there a way to clear out the Database when tests are complete?", point number 2 you have a link: http://www.andrewspencer.net/2011/solve-foreign-key-problems-in-dbunit-test-data/)

Closing parenthesis cause the problem.

**Comment by gavenkoa** [comment]
Blog has died, today it is: https://web.archive.org/web/20200218135648/http://www.andrewspencer.net:80/2011/solve-foreign-key-problems-in-dbunit-test-data
