### ISSUE TITLE
How can i avoid wrong datasource.

### ISSUE THREAD

**Issue by limeng32** [springtestdbunit/spring-test-dbunit#95]
Hi, i am from China so may be a little strange in my word.
I do a one-man project with springtestdbunit, and i had to switch from 4 datasources (volatile,dev,test and real) by maven profile. I found it`s hard to recognize the exact datasource using when i use "mvn clean test" in my module with inheritance relationships. It will be a disaster if i do dbunit test in my "real" datasource. So anyone could give me some good idea? A lot Thanks.

**Comment by mzagar** [comment]
Hi,

You could try one of the following:

- autowire spring environment in your test class and throw exception if current profile is not what it should be; [here's how you can determine active profiles programatically](http://stackoverflow.com/questions/28392231/how-to-determine-programmatically-the-current-active-profile-using-spring-boot)

- use [@IfProfileValue](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/annotation/IfProfileValue.html) together with SpringJUnit4ClassRunner to enable/disable running of specific test or test class when certain spring profiles are active (although this would help with not running the test in the wrong profile, it would probably hide the fact that you are running your test with the wrong profile)

Hope this helps.

**Comment by limeng32** [comment]
Thanks mzagar, the @IfProfileValue realily work.
It just deal half the problem, if my module inherited a wrong profiled jar, the right profile value just can't work. Finally I remove data source in _main_ and use another _test_ app.xml that have data source and include the _main_ one to solve.
By the way auto wire may be not work becouse I think spring test dbunit @datasetup annotation will run before it.
Best regards.
