### ISSUE TITLE
com.github.springtestdbunit.assertion.DatabaseAssertion throws Error instead of "promised" DatabaseUnitException when assertion fails!

### ISSUE THREAD

**Issue by evys42** [springtestdbunit/spring-test-dbunit#97]
An attempt to use `@ExpectedDatabase` annotation brought unexpected results when assertion fails: 
- transaction is not committed/rolled back;
- database connection stays open and is not released back to the pool;
- subsequent test has a good chance to get stuck waiting for the DB lock.

An offender seemed to be the `org.dbunit.Assertion.assertEquals(...)` methods, which throws `java.lang.Error` instead of promised `org.dbunit.DatabaseUnitException` when the assertion fails.

The assertion is invoked by 
```java
com.github.springtestdbunit.DbUnitTestExecutionListener.afterTestMethod(...).
```

In a `org.springframework.test.context.TestContextManager.afterTestMethod(...)` CALL to the configured test execution listeners is, naturally, surrounded by try/catch block that intercepts `java.lang.Exception`.  Unfortunately, when the listener throws a `java.lang.Error instead`, it escapes into surrounding `org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate()` method, preventing  the "downstream" listeners from being executed. One of the skipped listeners is, obviously, a `TransactionalTestExecutionListener`, responsible for ending a current transaction.

Filed similar issues with:
- spring: https://jira.spring.io/browse/SPR-13961
- dbunit: https://sourceforge.net/p/dbunit/bugs/381/

An easy workaround would be to use a DbUnitTestExecutionListener "extention":
```java
public class PeculiarDbUnitTestExecutionListener extends DbUnitTestExecutionListener {
	@Override
	public void afterTestMethod(TestContext testContext) throws Exception {
		try {
			super.afterTestMethod(testContext);
		} catch (Error e) {
			throw new DatabaseUnitException(e);
		}
	}
}
```

**Comment by philwebb** [comment]
It looks like this will be fixed in Spring 4.3 so I'd rather not put such hacks directly in `DbUnitTestExecutionListener`.
